sudo: required
dist: trusty
language: cpp
cache: apt

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8', 'valgrind']
      env: COMPILER=gcc-4.8 COMPILERXX=g++-4.8
    - compiler: clang
      addons:
        apt:
          packages: ['clang-3.5', 'valgrind']
      env: COMPILER=clang-3.5 COMPILERXX=clang++-3.5

before_install:
  - sudo apt-get install -yq python-dev
  - sudo apt-get install -yq python-pip
  - sudo pip install pyparsing

script: 
  - ( mkdir build && cd build && CC="$COMPILER" CXX="$COMPILERXX" cmake -DJOINT_VALGRIND=TRUE .. && make )
  - valgrind --suppressions=etc/valgrind.sup --tool=memcheck --leak-check=full --gen-suppressions=all --error-exitcode=1 ./build/bin/joint-test cpp tests-c
  - valgrind --suppressions=etc/valgrind.sup --tool=memcheck --leak-check=full --gen-suppressions=all --error-exitcode=1 ./build/bin/joint-test cpp tests-cpp
  - PYTHONPATH="`pwd`/test/python:`pwd`/build/bin" valgrind --suppressions=etc/valgrind.sup --tool=memcheck --leak-check=full --gen-suppressions=all --error-exitcode=1 ./build/bin/joint-test python Tests
