sudo: required
dist: trusty
language: cpp
cache: apt

addons:
  apt:
    packages: ['valgrind']

matrix:
  include:
    - compiler: gcc
      env: RUN_BENCHMARKS=1 BENCHMARKS_NUM_PASSES=10 BUILD_TYPE=RelWithDebInfo
    - compiler: gcc
      env: COVERITY_BUILD=1 BUILD_TYPE=RelWithDebInfo
    - compiler: gcc
      env: UPLOAD_COVERAGE=1 TEST_COVERAGE=1 BUILD_TYPE=Debug CMAKE_FLAGS="-DJOINT_COVERAGE=TRUE"
    - compiler: gcc
      env: USE_VALGRIND=1 BUILD_TYPE=Debug
    - compiler: clang
      addons:
        apt:
          packages: ['clang-3.5', 'valgrind']
      env: USE_VALGRIND=1 COMPILER=clang-3.5 COMPILERXX=clang++-3.5 BUILD_TYPE=Debug

before_install:
  - test "0$RUN_BENCHMARKS" -eq 0 || sudo apt-get install -yq libboost-all-dev
  - sudo apt-get install -yq mypy pep8 pylint python-coverage python-dev python-pip swig
  - sudo pip install jinja2 pylint-quotes pyparsing

install:
  - sudo apt-get install lcov
  - gem install coveralls-lcov
  - sudo pip install codecov
  - ./ci/do.sh prepare

script: 
  - ./ci/do.sh run

after_success:
  - ./ci/do.sh finalize
